<a href="https://colab.research.google.com/github/OjureFred/DataCentric/blob/main/Python_Programming_Numpy_Practice_Fred1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

### <font color="green">1.1 Challenge: Importing our Library</font>

In [1]:
# Let's import numpy
#
import numpy as np

### <font color="green">1.2 Challenge: Creating an Array</font>

In [3]:
# Challenge 1 
# Create an array of five zeros
#
import numpy as np
arr1 = np.array([0, 0, 0, 0, 0])
print(arr1)
arr2 = np.zeros(5)
print(arr2)

[0 0 0 0 0]
[0. 0. 0. 0. 0.]


In [5]:
# Challenge 2
# Create an array of six ones 
#
import numpy as np
arr1 = np.array([1, 1, 1, 1, 1, 1])
print(arr1)
arr2 = np.ones(6)
print(arr2)

[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]


In [8]:
# Challenge 3
# Create an array of the integers from 10 to 50
#
import numpy as np
arr1 = np.arange(10, 50, 5)
print(arr1)
arr2 = np.linspace(10,50,5)
print(arr2)

[10 15 20 25 30 35 40 45]
[10. 20. 30. 40. 50.]


In [14]:
# Challenge 4
# Create an array of odd integers from 20 to 60
#
import numpy as np
arr1 = np.arange(19,61, 2)
print(arr1)

[19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59]


In [16]:
# Challenge 5
# Create an array of 25 random numbers 
#
import numpy as np
arr1 = np.random.rand(25)
print(arr1)

[0.706562   0.33165055 0.96705174 0.6977895  0.20622243 0.67606889
 0.99293379 0.25806742 0.05089483 0.12825285 0.79227054 0.32108888
 0.6430072  0.25895955 0.68905689 0.49259    0.96269515 0.18827405
 0.14960817 0.90871859 0.27201739 0.33353623 0.13278462 0.12695505
 0.16508632]


### <font color="green">1.3 Working with Matrices</font>

In [26]:
# Challenge 6
# Write code to replicate the expected matrix output 
# of the cell shown below
# 
import numpy as np
arr = np.arange(1, 21)
print(arr)
arr2 = arr.reshape(5, 4)
print(arr2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 6: Expected Output
# [Do not run this cell]
# The output of this cell will disappear when run

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [38]:
# Challenge 7
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 
import numpy as np
arr1 = np.arange(14, 17)
arr2 = np.arange(18, 21)
#print(arr1)
#print(arr2)
arr3 = np.row_stack((arr1, arr2))

print(arr3)


[[14 15 16]
 [18 19 20]]


In [ ]:
# Challenge 7: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[14 15 16]
 [18 19 20]]


In [44]:
# Challenge 8
# Let's write code to replicate the expected matrix output 
# of the cell shown below
# 
import numpy as np
arr1 = np.arange(15, 21)
print(arr1)
arr2 = arr1[5]
print(arr2)

[15 16 17 18 19 20]
20


In [ ]:
# Challenge 8: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

20

In [47]:
# Challenge 9
# Let's write code to replicate the expected matrix output 
# of the cell shown below
#
import numpy as np
arr1 = np.arange(13, 21)
print(arr1)
arr2 = arr1.reshape(2,4)
print(arr2)

[13 14 15 16 17 18 19 20]
[[13 14 15 16]
 [17 18 19 20]]


In [ ]:
# Challenge 9: Expected Output
# [Do not run this cell]
# Running this cell will cause the output below to disappear

[[13 14 15 16]
 [17 18 19 20]]


In [58]:
# Challenge 10
# Let's find out the mean of first column values 
# in our matrix in challenge 6 above
# 
import numpy as np
arr = np.arange(1, 21)
print(arr)
arr2 = arr.reshape(5, 4)
print(arr2)
print()
print("Mean for all columns:")
print(arr2.mean(axis=0))
print()
print("Mean for first column:")
print(arr2.mean(axis=0)[0:1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Mean for all columns:
[ 9. 10. 11. 12.]

Mean for first column:
[9.]


In [63]:
# Challenge 11
# Let's find out the sum of second column values 
# in our matrix in challenge 6 above
#
import numpy as np
arr = np.arange(1, 21)
print(arr)
arr2 = arr.reshape(5, 4)
print(arr2)
print()
print("Sum of columns:")
print(arr2.sum(axis=0))
print()
print("Sum of second column:")
print(arr2.sum(axis=0)[1:2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Sum of columns:
[45 50 55 60]

Sum of second column:
[50]


In [64]:
# Challenge 12
# How do we find out the sum of all columns of the challenge 6 output
# The resulting array should contain the sums of each column
# 
import numpy as np
arr = np.arange(1, 21)
print(arr)
arr2 = arr.reshape(5, 4)
print(arr2)
print()
print("Sum of columns:")
print(arr2.sum(axis=0))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Sum of columns:
[45 50 55 60]
